//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public string Name { get; set; }
        public string MCI { get; set; }
        public Nullable<long> Fee { get; set; }
        public Nullable<long> Default { get; set; }
    }
}
