//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long RegNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string DoB { get; set; }
        public Nullable<long> Age { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Village { get; set; }
        public string Consultant { get; set; }
    }
}
