//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public string DrugName { get; set; }
        public string DrugForm { get; set; }
        public string Brand { get; set; }
        public string GenericName { get; set; }
        public string Route { get; set; }
        public string Frequency { get; set; }
        public Nullable<long> Days { get; set; }
    }
}
